
import java.sql.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class checkcourses extends javax.swing.JFrame {
Student st ;
home e ;
Connection conn ;
ResultSet rs ;
PreparedStatement pst ;
Courses s ;
 ArrayList<Courses> a = new ArrayList<>();
 ArrayList<String> b = new ArrayList<>();
 
    


    public checkcourses(Student st , home e,Courses s) {
        this.e = e ;
        this.st = st ;
        s = new Courses();
        this.s = s ;
       
        conn = Connect.con();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Course Code :");

        jButton1.setText("Check");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Prequsites of this course :");

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText(" It open this courses and if you drop the course they want open  :");

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(87, 87, 87)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(62, 62, 62)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 47, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (st.getMajor().equals("Industrial Systems Engineering")){
        String a = jTextField1.getText();
        String sql = "Select * from courses where  code ='"+a+"'"  ;
try{
    pst = conn.prepareStatement(sql);
    rs = pst.executeQuery();
     if(rs.next()){
     
                jLabel2.setText(rs.getString(4));
    
        
       
             
                   rs.close();
                   pst.close();
             
             
     }
    
    }   
catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
        }
        else if (st.getMajor().equals("Mechatronics Systems Engineering")){
                 String a = jTextField1.getText();
        String sql = "Select * from MechaCourses where  code ='"+a+"'"  ;
try{
    pst = conn.prepareStatement(sql);
    rs = pst.executeQuery();
     if(rs.next()){
                jLabel2.setText(rs.getString(4));
    
        
       
             
                   rs.close();
                   pst.close();
             
             
     }
    
    }   
catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
            
        }
          else if (st.getMajor().equals("Architecture Systems Engineering")){
                 String a = jTextField1.getText();
        String sql = "Select * from ArchitectureSystems  where  code ='"+a+"'"  ;
try{
    pst = conn.prepareStatement(sql);
    rs = pst.executeQuery();
     if(rs.next()){
                jLabel2.setText(rs.getString(4));
    
        
       
             
                   rs.close();
                   pst.close();
             
             
     }
    
    }   
catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
            
        }
         if(st.getMajor().equals("Industrial Systems Engineering")){
       try{ 
           String b = jTextField1.getText();
        String sql = "Select * from courses where  Prereq ='"+b+"'"   ;
        pst = conn.prepareStatement(sql);
        rs=pst.executeQuery();
        while(rs.next()){
            Courses s =new Courses();
           s.setCode(rs.getString("Code"));
           s.setSub(rs.getString("Subject"));
           a.add(s); 
        }
           rs.close();
           pst.close();
           
            
            
        }
       catch(Exception e){
            e.printStackTrace();
           JOptionPane.showMessageDialog(null, e);
       }
        
    }
        else if(st.getMajor().equals("Mechatronics Systems Engineering")){
            try{ 
                String b = jTextField1.getText();
        String sql = "Select * from MechaCourses where  Prereq ='"+b+"'";
        pst = conn.prepareStatement(sql);
        rs=pst.executeQuery();
        while(rs.next()){
            Courses s =new Courses();
           s.setCode(rs.getString("Code"));
           s.setSub(rs.getString("Subject"));
           a.add(s); 
        }
           rs.close();
           pst.close();
           
            
            
        }
       catch(Exception e){
            e.printStackTrace();
           JOptionPane.showMessageDialog(null, e);
       }
        }
         else if(st.getMajor().equals("Architecture Systems Engineering")){
            try{ 
                String b = jTextField1.getText();
        String sql = "Select * from ArchitectureSystems  where  Prereq ='"+b+"'";
        pst = conn.prepareStatement(sql);
        rs=pst.executeQuery();
        while(rs.next()){
            Courses s =new Courses();
           s.setCode(rs.getString("Code"));
           s.setSub(rs.getString("Subject"));
           a.add(s); 
        }
           rs.close();
           pst.close();
           
            
            
        }
       catch(Exception e){
            e.printStackTrace();
           JOptionPane.showMessageDialog(null, e);
       }
        }

         
    jComboBox1.setModel(new DefaultComboBoxModel(a.toArray( )));
    a.clear();
    
    
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         checkcourses.this.dispose();
        this.e.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       jTextField1.setText("");
           s.setCode("");
           s.setSub("");
       
        jComboBox1.setModel(new DefaultComboBoxModel(b.toArray(new String[0])));
        a.clear();
       jLabel2.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}